# language: node_js
# node_js:
#   - "stable"
arch:
  - arm64

sudo: required

services:
  - docker

# install
before_install:
  - echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin

# build
script:
  - docker build -t sthinds/trello-groomer . 
  # TODO: run tests

# deploy
after_success:
  - docker push sthinds/trello-groomer