sudo: required
services:
  - docker
language: bash

before_install:
  - echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
script:
  # prepare qemu
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # build image
  - docker build -t sthinds/trello-groomer . 
after_success:
  # deploy
  - docker push sthinds/trello-groomer