language: node_js
node_js:
  - "stable"

sudo: required

services:
  - docker

# install
before_install:
  - echo "BEFORE INSTALL"
  # TODO: set up environment?
  - echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin

# build
script:
  - echo "HELLO TRAVIS"
  - docker build -t trello-groomer:latest . 
  # TODO: run tests

# deploy
after_success:
  - echo "AFTER SUCCESS"
  # TODO: push to DockerHub
  - docker push sthinds/trello-groomer