language: node_js
node_js:
  - "stable"

sudo: required

services:
  - docker

# install
before_install:
  - echo "BEFORE INSTALL"

# build
script:
  - echo "HELLO TRAVIS"
  # TODO: run the Docker build
  - docker build -t trello-groomer:latest . 
  # TODO: run tests

# deploy
after_success:
  - echo "AFTER SUCCESS"
  # TODO: push to DockerHub