dist: xenial
sudo: required
env:
  global:
    - DOCKER_REPO=sthinds/trello-groomer
    - ARCHITECTURE_TARGETS=linux/arm/v7,linux/arm64,linux/amd64
before_install:
  # TODO: use service instead of this first line? stop and restart?
  - curl -fsSL https://get.docker.com | sh
  - echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
  - mkdir -p $HOME/.docker
  - echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
  - sudo service docker start
  - echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
install:
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  # TODO: what is this? necessary?
  - docker buildx create --name xbuilder --use
script: 
  - docker buildx build --progress plain --platform=$ARCHITECTURE_TARGETS -t $DOCKER_REPO --push .