name: Trigger Gitlab build Pipeline

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  trigger-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitLab Pipeline
        env:
          GITLAB_API_URL: "https://gitlab.sth144.duckdns.org/api/v4/projects/2/pipeline"
        run: |
          curl \
            -X POST \
            -H "Private-Token: $GITLAB_ACCESS_TOKEN" \
            -H "Content-Type: application/json" \
            --data "ref=master" \
            $GITLAB_API_URL
