name: Trigger Gitlab build Pipeline

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  trigger-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitLab Pipeline
        env:
          GITLAB_API_TOKEN: ${{ secrets.GITLAB_API_TOKEN }}
          GITLAB_API_URL: "https://gitlab.sth144.duckdns.org/api/v4/projects/1/trigger/pipeline"
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        run: |
          echo $GITLAB_API_TOKEN
          curl \
            -X POST \
            --form "token=$GITLAB_API_TOKEN" \
            --form "ref=main" \
            --form "variables[BRANCH]=$BRANCH_NAME" \
            --form "variables[REPO]=trello-groomer" \
            $GITLAB_API_URL
